<?php

namespace TweetCount\ApiBundle\Form;

use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\UrlType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\AbstractType;

class TCUrlType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('url', UrlType::class, array(
            'required' => false
        ));

        $builder->add('apikey', TextType::class, array(
            'required' => false
        ));
    }


    public function setDefaultOptions(OptionsResolverInterface $resolver) {

    }

    public function getParent()
    {
        return parent::getParent(); // TODO: Change the autogenerated stub
    }

    public function getName() {
        return "";
    }
}
