tweet_count_website:
    resource: "@TweetCountWebsiteBundle/Resources/config/routing.yml"
    prefix:   /

tweet_count_api:
    resource: "@TweetCountApiBundle/Resources/config/routing.yml"
    prefix:   /api/
